name: memorise
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_slidable: ^3.1.0
  hydrated_bloc: ^9.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  meta: ^1.9.1
  bloc: ^8.1.2
  flutter_local_notifications: ^17.0.0
  flutter_timezone: ^1.0.8
  rxdart: ^0.27.7
  path_provider: ^2.0.15
  path_provider_aurora:
    git:
      url: https://gitlab.com/omprussia/flutter/flutter-plugins.git
      ref: path_provider_aurora-0.0.1
      path: packages/path_provider/path_provider_aurora


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
